version: 0.2

env:
  variables:
    AWS_REGION: "us-east-1"
    REACT_APP_USERS_SERVICE_URL: "good-driver-app-alb-589375039.us-east-1.elb.amazonaws.com"

phases:
  install:
    runtime-versions:
      docker: 18
  pre_build:
    commands:
      - echo logging in to ecr...
      - $(aws ecr get-login --no-include-email --region $AWS_REGION)
      - docker pull $AWS_ACCOUNT_ID.dkr.ecr.$AWS_REGION.amazonaws.com/good-driver-app-server:prod || true
      # - docker pull $AWS_ACCOUNT_ID.dkr.ecr.$AWS_REGION.amazonaws.com/good-driver-app-client:builder || true
      - docker pull $AWS_ACCOUNT_ID.dkr.ecr.$AWS_REGION.amazonaws.com/good-driver-app-client:prod || true
  build:
    commands:
      - echo building and testing dev images...
      - docker-compose up -d --build
      # - docker-compose exec -T server python -m pytest "project/tests" -p no:warnings --cov="project"
      # - docker-compose exec -T server flake8 project
      # - docker-compose exec -T server black project --check
      # - docker-compose exec -T server /bin/sh -c "isort project/*/*.py --check-only"
      # - docker-compose exec -T client npm run lint
      # - docker-compose exec -T client npm run prettier:check
      # - docker-compose exec -T client npm run prettier:write
      - echo building prod images...
      - >
        docker build \
          -f services/server/Dockerfile.prod \
          -t $AWS_ACCOUNT_ID.dkr.ecr.$AWS_REGION.amazonaws.com/good-driver-app-server:prod \
          ./services/server
      - >
        docker build \
          -f services/client/Dockerfile.prod \
          -t $AWS_ACCOUNT_ID.dkr.ecr.$AWS_REGION.amazonaws.com/good-driver-app-client:prod \
          --build-arg NODE_ENV=production \
          --build-arg REACT_APP_USERS_SERVICE_URL=$REACT_APP_USERS_SERVICE_URL \
          ./services/client
  post_build:
    commands:
    - echo pushing prod images to ecr...
    - docker push $AWS_ACCOUNT_ID.dkr.ecr.$AWS_REGION.amazonaws.com/good-driver-app-server:prod
    # - docker push $AWS_ACCOUNT_ID.dkr.ecr.$AWS_REGION.amazonaws.com/good-driver-app-client:builder
    - docker push $AWS_ACCOUNT_ID.dkr.ecr.$AWS_REGION.amazonaws.com/good-driver-app-client:prod