version: '3.7'

services:

  server:
    build:
      context: ./services/server
      dockerfile: Dockerfile
    entrypoint: ['/usr/src/app/entrypoint.sh']
    volumes:
      - './services/server:/usr/src/app'
    ports:
      - 5001:5000
    env_file:
      - dev_env.env

    depends_on:
      - good-driver-db

  good-driver-db:
    build:
      context: ./services/server/project/db
      dockerfile: Dockerfile
    expose:
      - 5432
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    volumes:
      - db-data:/var/lib/postgresql/data

  client:
    build:
      context: ./services/client
      dockerfile: Dockerfile
    volumes:
      - './services/client:/usr/src/app'
      - '/usr/src/app/node_modules'
    ports:
      - 3007:3000
    environment:
      - NODE_ENV=development
      - REACT_APP_USERS_SERVICE_URL=${REACT_APP_USERS_SERVICE_URL}
      - CHOKIDAR_USEPOLLING=true
    depends_on:
      - server

volumes:
  db-data:
      