version: '3.7'

services:

  server:
    build:
      context: ./services/server
      dockerfile: Dockerfile.prod
    ports:
      - 5001:5000
    environment:
      - FLASK_ENV=production
      - APP_SETTINGS=project.config.ProductionConfig
      - DATABASE_URL=postgres://postgres:postgres@good-drivers-db:5432/good_drivers_prod
      - DATABASE_TEST_URL=postgres://postgres:postgres@good-drivers-db:5432/good_drivers_test
      - SECRET_KEY=my_precious
    depends_on:
      - good-drivers-db

  good-drivers-db:
    build:
      context: ./services/server/project/db
      dockerfile: Dockerfile
    expose:
      - 5432
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres

  client:
    build:
      context: ./services/client
      dockerfile: Dockerfile.prod
      args:
        - NODE_ENV=production
        - REACT_APP_USERS_SERVICE_URL=${REACT_APP_USERS_SERVICE_URL}
    ports:
      - 3007:80
    depends_on:
      - server